apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-hello-deployment
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-hello
  template:
    metadata:
      labels:
        app: react-hello
    spec:
      containers:
      - name: react-hello
        image: react-hello/app:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4040

---

apiVersion: v1
kind: Service
metadata:
  name: react-hello
  namespace: devops
spec:
  selector:
    app: react-hello
  ports:
  - port: 4040
    targetPort: 4040
    name: tcp

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-hello-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingressClassName: "traefik"
spec:
  rules:
  - host: "www.192.168.56.2.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: react-hello
            port: 
              number: 4040